apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-1
spec:
  containers:
  - name: gpu-container
    image: tovitu/hlmice-yolo:latest
    command: ["sleep", "infinity"]
    resources:
      requests:
        cpu: "1"
        memory: "16Gi"
      limits:
        cpu: "8"
        memory: "32Gi"
        nvidia.com/gpu: 1
    env:
      - name: "SUBDIR"
        value: "CAF42"
      - name: "VIDEODIR"
        value: "s3://hengenlab/yolo_videos/"
      - name: "ENDPOINT"
        value: "https://s3-central.nrp-nautilus.io"
      - name: "MODELNAME"
        value: "homecage_best.pt"
      - name: "ID"
        value: "${ID}"
      - name: "SUBDIR_LOWERCASE"
        value: "${SUBDIR_LOWERCASE}"
    volumeMounts:
      - name: "prp-s3-credentials"
        mountPath: "/root/.aws/credentials"
        subPath: "credentials"

  volumes:
    - name: external
      persistentVolumeClaim:
        claimName: tovi-vol
    - name: prp-s3-credentials
      secret:
        secretName: prp-s3-credentials
  

    
