apiVersion: batch/v1
kind: Job
metadata:
  name: tovitu-yolo-post-process
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never  # Never | OnFailure

      containers:
      - name: tovitu-container
        image: tovitu/hlmice-yolo:latest
        imagePullPolicy: Always

        resources:
          requests:
            cpu: "1"
            memory: "16Gi"
          limits:
            cpu: "8"
            memory: "32Gi"

        command: ["stdbuf", "-oL", "-eL", "/bin/bash", "-c"]
        args:
          - >-
            bash scripts/process_detected.sh;
            
        env:
          - name: "SUBDIR"
            value: "prey_capture"
          - name: "VIDEODIR"
            value: "s3://hengenlab/yolo_videos/"
          - name: "ENDPOINT"
            value: "https://s3-central.nrp-nautilus.io"
          - name: "MODELNAME"
            value: "best.pt"
          - name: "ID"
            value: "${ID}"

        volumeMounts:
          - name: "prp-s3-credentials"
            mountPath: "/root/.aws/credentials"
            subPath: "credentials"

      tolerations:
        - key: "nautilus.io/chase-ci"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
          
      volumes:
        - name: prp-s3-credentials
          secret:
            secretName: prp-s3-credentials
    
