apiVersion: batch/v1
kind: Job
metadata:
  name: yolo-predict-11
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never  # Never | OnFailure

      containers:
      - name: yolo-predict-cont-11
        image: marksongtech/hl:0.0.5
        imagePullPolicy: Always

        resources:
          requests:
            cpu: "14"
            memory: "60Gi"
            ephemeral-storage: "170Gi"
          limits:
            cpu: "16"
            memory: "64Gi"
            nvidia.com/gpu: 1
            ephemeral-storage: "200Gi"

        command: ["stdbuf", "-oL", "-eL", "/bin/bash", "-c"]
        args:
          - >-
            bash scripts/detect_parallel.sh;
            
        env:
          - name: "SUBDIR" # Yolo Data
            value: "aj_ris" #ChangeMe
          - name: "SUBDIR_DLC" # DLC Data
            value: "aj_ris" #ChangeMe
          - name: "VIDEODIR"
            value: "s3://hengenlab/yolo_videos/"
          - name: "ENDPOINT"
            value: "https://s3-central.nrp-nautilus.io"
          - name: "MODELNAME"
            value: "homecage_best.pt" #ChangeMe best.pt or homecage_best.pt
          - name: "MAX_JOBS"
            value: "10"

        volumeMounts:
          - name: "prp-s3-credentials"
            mountPath: "/root/.aws/credentials"
            subPath: "credentials"

      tolerations:
        - key: "nautilus.io/chase-ci"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
          
      volumes:
        - name: prp-s3-credentials
          secret:
            secretName: prp-s3-credentials
    
