apiVersion: batch/v1
kind: Job
metadata:
  name: tovitu-yolo-predict
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never  # Never | OnFailure

      containers:
      - name: tovitu-container
        image: tovitu/hlmice-yolo:latest
        imagePullPolicy: Always

        resources:
          requests:
            cpu: "1"
            memory: "32Gi"
          limits:
            cpu: "8"
            memory: "64Gi"
            nvidia.com/gpu: 1

        command: ["stdbuf", "-oL", "-eL", "/bin/bash", "-c"]
        args:
          - >-
            aws s3 --endpoint $ENDPOINT cp s3://hengenlab/yolo/model/best.pt /models/best.pt;
            aws s3 --endpoint $ENDPOINT cp s3://hengenlab/yolo_videos/JMG5_2A-20221122T104018-114018.mp4 /datasets/JMG5_2A-20221122T104018-114018.mp4;
            python yolov5/detect.py --exist-ok --weights /models/best.pt --source /datasets/JMG5_2A-20221122T104018-114018.mp4 --save-csv --save-txt &&
            zip -r result.zip yolov5/runs/detect/exp;
            aws s3 --endpoint $ENDPOINT cp result.zip s3://hengenlab/yolo/results/
            
        env:
          - name: "DATANAME"
            value: "/external/"
          - name: "ENDPOINT"
            value: "https://s3-central.nrp-nautilus.io"

        volumeMounts:
          - name: "prp-s3-credentials"
            mountPath: "/root/.aws/credentials"
            subPath: "credentials"

      tolerations:
        - key: "nautilus.io/chase-ci"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
          
      volumes:
        - name: prp-s3-credentials
          secret:
            secretName: prp-s3-credentials
    
